### ISSUE TITLE
npm start error pointing to issue with conversation-simple package

### ISSUE THREAD

**Issue by asidd** [watson-developer-cloud/conversation-simple#113]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart conversation-simple@0.1.1
6 info start conversation-simple@0.1.1
7 verbose unsafe-perm in lifecycle true
8 info conversation-simple@0.1.1 Failed to exec start script
9 verbose stack Error: conversation-simple@0.1.1 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid conversation-simple@0.1.1
11 verbose cwd /Users/adithyanayabu1/Documents/Technology-Learn/ChatBots/virtual-ta-chatbot
12 error Darwin 16.1.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error conversation-simple@0.1.1 start: `node server.js`
17 error Exit status 1
18 error Failed at the conversation-simple@0.1.1 start script 'node server.js'.
18 error This is most likely a problem with the conversation-simple package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls conversation-simple
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
 
```

**Comment by ttlew** [comment]
@stevenpkg can you please take a look?

**Comment by germanattanasio** [comment]
closing due inactivity
