### ISSUE TITLE
Failure at NPM start

### ISSUE THREAD

**Issue by Samgill175** [watson-developer-cloud/conversation-simple#151]
Hello, after following the steps within the ReadMe my npm start is failing. I'm getting the following error. I've altered the .env file to include the correct security credentials for the appropriate workspace.
```
conversation-simple@0.1.1 start C:\Users\SamuelGilliland\Desktop\conversation-simple-AVA\conversation-simple-AVA
> node server.js

C:\Users\SamuelGilliland\Desktop\conversation-simple-AVA\conversation-simple-AVA\node_modules\watson-developer-cloud\lib\base_service.js:73
      throw new Error('Argument error: username and password are required unless use_unauthenticated is set');
      ^

Error: Argument error: username and password are required unless use_unauthenticated is set
    at ConversationV1.BaseService.initCredentials (C:\Users\SamuelGilliland\Desktop\conversation-simple-AVA\conversation-simple-AVA\node_modules\watson-developer-cloud\lib\base_service.js:73:13)
    at ConversationV1.BaseService (C:\Users\SamuelGilliland\Desktop\conversation-simple-AVA\conversation-simple-AVA\node_modules\watson-developer-cloud\lib\base_service.js:44:18)
    at new ConversationV1 (C:\Users\SamuelGilliland\Desktop\conversation-simple-AVA\conversation-simple-AVA\node_modules\watson-developer-cloud\conversation\v1.js:31:15)
    at Object.<anonymous> (C:\Users\SamuelGilliland\Desktop\conversation-simple-AVA\conversation-simple-AVA\app.js:30:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! conversation-simple@0.1.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the conversation-simple@0.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SamuelGilliland\AppData\Roaming\npm-cache\_logs\2018-02-06T20_39_12_810Z-debug.log
```

**Comment by germanattanasio** [comment]
You need to specify your service credentials. The error is saying that you didn't specify username and password

**Comment by Samgill175** [comment]
Yep, the issue was that was the .env file wasn't saved properly. Issue resolved.
