### ISSUE TITLE
 Unable to start the app : Failed at the @ start script.

### ISSUE THREAD

**Issue by PhilippeComte** [watson-developer-cloud/conversation-simple#259]
Hello , 
following the instructions, I did :  npm install
At npm start I get : dotenv missing 
I installed : npm dotenv 
Then it is express that is lacking 
I've installed the latest node 12.18.0 and npm 6.14.4
and installed  express and express generator 
Sudo npm install -g express
Sudo npm install -g express-generator

I got issues  at npm start 
Failed at the @ start script.

Is it something that others have seen ? 

here is the log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v12.18.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 info lifecycle @~start: @
7 verbose lifecycle @~start: unsafe-perm in lifecycle true
8 verbose lifecycle @~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/pcomte/Documents/GitHub/assistant-simple/node_modules/.bin:/Users/pcomte/anaconda3/bin:/Users/pcomte/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/apache-maven-3.6.0/bin:/Users/pcomte/python/mes_scripts
9 verbose lifecycle @~start: CWD: /Users/pcomte/Documents/GitHub/assistant-simple
10 silly lifecycle @~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle @~start: Returned: code: 1  signal: null
12 info lifecycle @~start: Failed to exec start script
13 verbose stack Error: @ start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @
15 verbose cwd /Users/pcomte/Documents/GitHub/assistant-simple
16 verbose Darwin 19.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v12.18.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error @ start: `node server.js`
22 error Exit status 1
23 error Failed at the @ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Many thanks .

**Comment by germanattanasio** [comment]
Hi @PhilippeComte.

If you run `npm install` you should get all the dependencies you need including [`dotenv`](https://github.com/watson-developer-cloud/assistant-simple/blob/master/package.json#L23)

The fact that you got an error on the dependencies makes me think that you are not running the command in the folder where the code is

**Comment by nightdvlpr** [comment]
I have the same issue:
`
11 silly lifecycle mayagroupapi@0.0.0~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle mayagroupapi@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle mayagroupapi@0.0.0~start: Failed to exec start script
14 verbose stack Error: mayagroupapi@0.0.0 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/opt/alt/alt-nodejs10/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:198:13)
14 verbose stack     at ChildProcess.<anonymous> (/opt/alt/alt-nodejs10/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:198:13)
14 verbose stack     at maybeClose (internal/child_process.js:982:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
15 verbose pkgid mayagroupapi@0.0.0
16 verbose cwd /home/nelsonva/data.mayaexchange.ca
17 verbose Linux 4.18.0-147.8.1.el7h.lve.1.x86_64
18 verbose argv "/opt/alt/alt-nodejs10/root/usr/bin/node" "/opt/alt/alt-nodejs10/root/usr/bin/npm" "run-script" "start" "--"
19 verbose node v10.24.1
20 verbose npm  v6.14.12
21 error code ELIFECYCLE
22 error errno 1
23 error mayagroupapi@0.0.0 start: `node ./bin/www`
23 error Exit status 1
24 error Failed at the mayagroupapi@0.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
`
